### ISSUE TITLE
Use sequences obtained from termcap(5), not hardcoded ones.

### ISSUE THREAD

**Issue by weshatheleopard** [piotrmurach/tty-cursor#11]
From what I see in the code, ESC-sequences are [hardcoded](https://github.com/piotrmurach/tty-cursor/blob/master/lib/tty/cursor.rb#L11) which in general is not correct, as they should be obtained from the system configuration instead -- see [termcap(5)](https://linux.die.net/man/5/termcap).

**Comment by piotrmurach** [comment]
Thanks for the issue report.

This gem powers pretty much all of the `tty` components, which are tested on few operating systems(Windows, macOS and Debian Linux). I have never seen any reports about these sequences not working correctly. In my experience pretty much all modern terminal emulators support these escape codes. Have you found a case when this is not true? I'm not keen on making specific system calls to gather any information about what are POSIX standard codes. This seems heavy-handed and unnecessary.

**Comment by weshatheleopard** [comment]
"I have never seen..." is a poor argument; I have never seen a penguin with my own eyes, but that doesn't mean they do not exist. Standards are out there for a specific reason: so they are followed, and nobody is left behind. For one example, [PuTTY](https://en.wikipedia.org/wiki/PuTTY) supports five different terminals.

I *do* understand that you don't want to be bothered with things that are unimportant to you, and that is fine. When I get around to it, I will submit a PR.
