### ISSUE TITLE
clear_screen doesn't seem to do anything

### ISSUE THREAD

**Issue by monkeysuffrage** [piotrmurach/tty-cursor#2]
I'm sure I'm misunderstanding something. My code looks like:
cursor = TTY::Cursor
puts "this should get cleared, right?"
cursor.clear_screen
I expect the line to be cleared. What am I missing?

**Comment by drogus** [comment]
`TTY::Cursor.clear_screen` generates an ANSI sequence to clear screen, you need to print it to the screen yourself:

```ruby
print TTY::Cursor.clear_screen
```

should work

**Comment by piotrmurach** [comment]
Thanks @drogus
