### ISSUE TITLE
Mac OS's Terminal.app does not support #save and #restore

### ISSUE THREAD

**Issue by austb** [piotrmurach/tty-cursor#3]
Terminal.app does not support the save and restore codes `"\e[s"` and `"\e[u"`.

It does however support the other codes `"\e7"` and `"\e8"` (no `[` in those commands). It appears that most other terminal emulators support these escape sequences as well as the above CSI codes.

**Comment by austb** [comment]
List of terminal emulators I have tested for support.

1. tmux
2. sles 12
3. centos 7
4. Fedora 24
5. Redhat 6 (did not see cursor movement, probably due to not flushing the output but end result the same)

Additional terminals that do not support "\e[s" format, but do support "\e7" format

1. Debian 8

**Comment by austb** [comment]
Windows Powershell (w/ ansicon.exe) does not support "\e7" and "\e8" so if this is changed, it should also contain a windows workaround using "\e[s" and "\e[u"

**Comment by austb** [comment]
ConEmu appears to [support both](http://conemu.github.io/en/AnsiEscapeCodes.html#C1_Control_Chars)

**Comment by austb** [comment]
This script shows that most terminals have save_cursor defined as "\e7", and as a result support for "\e[s" is not guaranteed.

**Warning**, this is a lot of text output.
```bash
#!/usr/bin/env bash
#

for folder in /usr/share/terminfo/*; do
  for term in $folder/*; do
    filename=$(basename $term)
    value="$(infocmp -L1 "$filename" | grep save_cursor)"

    echo "$folder/$filename -> $value"
  done
done
```

**Comment by piotrmurach** [comment]
Thanks, that's some good investigation ❤️  
Sorry to be less responsive, just been moving my flat and my back hurts...
