### ISSUE TITLE
Problem with TTY::Cursor.clear_screen

### ISSUE THREAD

**Issue by jitlogan** [piotrmurach/tty-cursor#9]
Hi, maybe im wrong with something. When i call .clear_screen it produces "\e[2j". This escape sequence does not move cursor to the home position at least in my terminal. When i manually print "\e[H\e[2J" it goes home.

**Comment by piotrmurach** [comment]
Hi,

The behaviour is correct. I've implemented this library according to vt100 terminal standard which states that "<esc>[2J" escape code "Erases the screen with the background colour and moves the cursor to home." [see details](http://www.termsys.demon.co.uk/vtansi.htm) The `move_to` call is used to positioning cursor. Therefore, in your case the following will work fine in any case:

```ruby
print cursor.clear_screen + cursor.move_to(0,0)
```

**Comment by jitlogan** [comment]
Ok, thank you for your work.
